# Generated by Django 5.1.3 on 2025-12-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('product_id', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
